// Curated image manifest — every image is from Wikimedia Commons with a
// verified free license. merge.mjs folds this into research.json as `images`;
// the template renders credits in Sources & method. Files live in images/.
// alt = accessibility; caption = printed under the image; credit/license = attribution.

export const IMAGES = [
  {
    slug: "cover",
    file: "images/cover.jpg",
    alt: "Tallinn skyline at night, the medieval old town lit against a dark sky",
    caption: "Tallinn at night — a medieval old town wrapped around a digital state.",
    credit: "Zvpunry",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Tallinn_at_night.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tallinn_at_night.jpg/1920px-Tallinn_at_night.jpg",
  },
  {
    slug: "aerial",
    file: "images/aerial.jpg",
    alt: "Aerial view of Tallinn, Estonia",
    caption: "The whole market, from above. Tallinn holds a third of Estonia's 1.37 million people.",
    credit: "kallerna",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Tallinn_aerial_2022.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Tallinn_aerial_2022.jpg/1920px-Tallinn_aerial_2022.jpg",
  },
  {
    slug: "ulemiste",
    file: "images/ulemiste.jpg",
    alt: "Modern office buildings of Ülemiste City technology campus in Tallinn",
    caption: "Ülemiste City — Tallinn's largest tech campus, built on a former industrial estate.",
    credit: "Liilia Moroz",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:%C3%9Clemiste_City_2022.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/%C3%9Clemiste_City_2022.jpg/1920px-%C3%9Clemiste_City_2022.jpg",
  },
  {
    slug: "telliskivi",
    file: "images/telliskivi.jpg",
    alt: "Telliskivi Creative City, converted industrial buildings in Tallinn",
    caption: "Telliskivi Creative City — the converted rail-yard district at the heart of Tallinn's startup scene.",
    credit: "Ivo Kruusamägi",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Telliskivi_(2023)_-_002.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Telliskivi_%282023%29_-_002.jpg/1920px-Telliskivi_%282023%29_-_002.jpg",
  },
  {
    slug: "starship-tartu",
    file: "images/starship-tartu.jpg",
    alt: "A Starship delivery robot on a street in central Tartu, Estonia, 2017",
    caption: "A Starship delivery robot in central Tartu, 2017 — autonomy as street furniture.",
    credit: "Sillerkiil",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Idufirma_Starship_pakirobot_Tartu_kesklinnas_2017._aastal..jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Idufirma_Starship_pakirobot_Tartu_kesklinnas_2017._aastal..jpg/1920px-Idufirma_Starship_pakirobot_Tartu_kesklinnas_2017._aastal..jpg",
  },
  {
    slug: "starship-winter",
    file: "images/starship-winter.jpg",
    alt: "A Starship delivery robot driving through snow",
    caption: "A Starship robot at work in winter. The fleet has made millions of autonomous deliveries.",
    credit: "Mbrickn",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Starship_Robot_in_Winter.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Starship_Robot_in_Winter.jpg/1280px-Starship_Robot_in_Winter.jpg",
  },
  {
    slug: "eres-card",
    file: "images/eres-card.jpg",
    alt: "An Estonian e-Residency starter kit with digital ID card",
    caption: "The e-Residency kit — a country, issued as a card and a PIN.",
    credit: "Masayuki (Yuki) Kawagishi",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:E-Residency_card.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/E-Residency_card.jpg/1920px-E-Residency_card.jpg",
  },
  {
    slug: "id-card",
    file: "images/id-card.jpg",
    alt: "An Estonian digital identity card issued to an e-resident, 2022",
    caption: "The cryptographic ID card — the keystone of the e-state. Every signature it makes is legally binding.",
    credit: "Lamb104",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Estonian_Digital_Identity_Card_Issued_to_E-Resident_-_Issued_2022.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Estonian_Digital_Identity_Card_Issued_to_E-Resident_-_Issued_2022.jpg/1920px-Estonian_Digital_Identity_Card_Issued_to_E-Resident_-_Issued_2022.jpg",
  },
  {
    slug: "tartu",
    file: "images/tartu.jpg",
    alt: "The neoclassical main building of the University of Tartu",
    caption: "The University of Tartu, founded 1632. Playtech and Skype's engine both trace back to this town.",
    credit: "Ivar Leidus",
    license: "CC BY-SA 3.0 EE",
    source: "https://commons.wikimedia.org/wiki/File:Tartu_%C3%9Clikooli_peahoone_2012.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Tartu_%C3%9Clikooli_peahoone_2012.jpg/1920px-Tartu_%C3%9Clikooli_peahoone_2012.jpg",
  },
  {
    slug: "bolt-scooter",
    file: "images/bolt-scooter.jpg",
    alt: "A Bolt electric scooter parked on a city street",
    caption: "Bolt hardware on the street. The Tallinn-built super-app runs rides, scooters and delivery in 50+ countries.",
    credit: "RickRichards",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bolt_electric_scooter.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Bolt_electric_scooter.jpg/1920px-Bolt_electric_scooter.jpg",
  },
  {
    slug: "ccdcoe",
    file: "images/ccdcoe.jpg",
    alt: "Estonian and NATO flags at the Cooperative Cyber Defence Centre of Excellence in Tallinn",
    caption: "NATO's cyber-defence centre, Tallinn — the institutional payoff of the 2007 attacks.",
    credit: "Tony Webster",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:CCDCOE_Estonia_and_NATO_Flags_(53861557427).jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/CCDCOE_Estonia_and_NATO_Flags_%2853861557427%29.jpg/1920px-CCDCOE_Estonia_and_NATO_Flags_%2853861557427%29.jpg",
  },
  {
    slug: "bronze",
    file: "images/bronze.jpg",
    alt: "The Bronze Soldier monument in Tallinn, 2007",
    caption: "The Bronze Soldier, 2007. Moving it triggered riots — and the cyberattacks that built a doctrine.",
    credit: "gette",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bronze_Soldier_of_Tallinn,_2007.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Bronze_Soldier_of_Tallinn%2C_2007.jpg/1920px-Bronze_Soldier_of_Tallinn%2C_2007.jpg",
  },
  {
    slug: "meri",
    file: "images/meri.jpg",
    alt: "Lennart Meri, President of Estonia 1992–2001",
    caption: "Lennart Meri, the president who announced Tiger Leap on national television in 1996.",
    credit: "Jens-Olaf Walter",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:Lennart_Meri_1929-2006.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Lennart_Meri_1929-2006.jpg",
  },
  // brand wordmarks (public-domain text logos, hosted on Commons)
  {
    slug: "logo-skype",
    file: "images/logo-skype.svg",
    alt: "Skype wordmark",
    caption: "",
    credit: "Skype wordmark — a Microsoft trademark",
    license: "Public domain (text logo)",
    source: "https://commons.wikimedia.org/wiki/File:Skype_logo_(fully_transparent).svg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Skype_logo_%28fully_transparent%29.svg",
  },
  {
    slug: "logo-wise",
    file: "images/logo-wise.svg",
    alt: "Wise wordmark",
    caption: "",
    credit: "Wise wordmark — a Wise plc trademark",
    license: "Public domain (text logo)",
    source: "https://commons.wikimedia.org/wiki/File:New_Wise_(formerly_TransferWise)_logo.svg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/8/81/New_Wise_%28formerly_TransferWise%29_logo.svg",
  },
  // founder portraits (identity-verified files only)
  {
    slug: "founder-ilves",
    file: "images/founder-ilves.jpg",
    alt: "Toomas Hendrik Ilves, President of Estonia 2006–2016",
    caption: "",
    credit: "Chatham House",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:Toomas_Hendrik_Ilves,_President_of_Estonia_(25502212355).jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Toomas_Hendrik_Ilves%2C_President_of_Estonia_%2825502212355%29.jpg/1280px-Toomas_Hendrik_Ilves%2C_President_of_Estonia_%2825502212355%29.jpg",
  },
  {
    slug: "founder-jaan-tallinn",
    file: "images/founder-jaan-tallinn.jpg",
    alt: "Jaan Tallinn, founding engineer of Skype",
    caption: "",
    credit: "Christopher Michel",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:Jaan_Tallinn_2014.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/4/43/Jaan_Tallinn_2014.jpg",
  },
  {
    slug: "founder-kristo-kaarmann",
    file: "images/founder-kristo-kaarmann.jpg",
    alt: "Kristo Käärmann, co-founder and CEO of Wise",
    caption: "",
    credit: "Estonian Foreign Ministry",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kristo_K%C3%A4%C3%A4rmann_2025.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Kristo_K%C3%A4%C3%A4rmann_2025.jpg/1280px-Kristo_K%C3%A4%C3%A4rmann_2025.jpg",
  },
  {
    slug: "founder-sten-tamkivi",
    file: "images/founder-sten-tamkivi.jpg",
    alt: "Sten Tamkivi speaking at Arvamusfestival, 2015",
    caption: "",
    credit: "Kärt Vajakas",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sten_Tamkivi,_Arvamusfestival_2015.jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Sten_Tamkivi%2C_Arvamusfestival_2015.jpg",
  },
  {
    slug: "founder-taavet-hinrikus",
    file: "images/founder-taavet-hinrikus.jpg",
    alt: "Taavet Hinrikus speaking at the opening of the 'Unity' dome, Brussels, 2017",
    caption: "",
    credit: "Tauno Tõhk / EU2017EE",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:Opening_of_the_'Unity'_dome_in_Justus_Lipsius_building_(35836648165).jpg",
    objpos: "68% center",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Opening_of_the_%27Unity%27_dome_in_Justus_Lipsius_building_%2835836648165%29.jpg/1280px-Opening_of_the_%27Unity%27_dome_in_Justus_Lipsius_building_%2835836648165%29.jpg",
  },
  {
    slug: "founder-kaarel-kotkas",
    file: "images/founder-kaarel-kotkas.jpg",
    alt: "Kaarel Kotkas, co-founder and CEO of Veriff, on centre stage at Web Summit Rio 2025",
    caption: "",
    credit: "Sam Barnes / Web Summit via Sportsfile",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:SAM_1919_(54483214111).jpg",
    objpos: "45% center",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/SAM_1919_%2854483214111%29.jpg/1280px-SAM_1919_%2854483214111%29.jpg",
  },
  {
    slug: "founder-markus-villig",
    file: "images/founder-markus-villig.jpg",
    alt: "Markus Villig, founder and CEO of Bolt, on stage at Web Summit 2022",
    caption: "",
    credit: "Web Summit",
    license: "CC BY 2.0",
    source: "https://commons.wikimedia.org/wiki/File:2022_-_Centre_Stage_RC2_8940_(52472376160).jpg",
    remote: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/2022_-_Centre_Stage_RC2_8940_%2852472376160%29.jpg/1280px-2022_-_Centre_Stage_RC2_8940_%2852472376160%29.jpg",
  },
];

// where each image is used (template reads these by slug)
export const IMAGE_SLOTS = {
  cover: "cover",
  breaks: ["telliskivi", "aerial"],
  forces: {
    "digital-state": "id-card",
    "skype-mafia": "ulemiste",
    education: "tartu",
    "e-residency": "eres-card",
    "small-market": "aerial",
    "ai-nation": "starship-tartu",
  },
  companies: { bolt: "bolt-scooter", starship: "starship-winter", skype: "logo-skype", wise: "logo-wise" },
  founders: {
    ilves: "founder-ilves",
    "jaan-tallinn": "founder-jaan-tallinn",
    "taavet-hinrikus": "founder-taavet-hinrikus",
    "kristo-kaarmann": "founder-kristo-kaarmann",
    "kaarel-kotkas": "founder-kaarel-kotkas",
    "sten-tamkivi": "founder-sten-tamkivi",
    "markus-villig": "founder-markus-villig",
  },
  timeline: { 1996: "meri", 2007: "bronze", 2008: "ccdcoe", 2014: "eres-card" },
};
